<?php

use Illuminate\Database\Seeder;

class OldUsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('users')->truncate();

        $oldUsers = array(
            array( // row #0
                'id' => 1,
                'user_name' => 'Воскан',
                'email' => 'info@voskan-voskanyan.ru',
                'google_id' => '',
                'user_img' => 'd8ca083788944f2614ca5c571d12e2e9.jpg',
                'desc' => '',
                'password' => 'fd9280bc68d29f9becaaa62fc86bcbe8',
                'user_type_id' => 3,
                'doljnost' => 'Программист',
                'delete' => '1',
            ),
            array( // row #1
                'id' => 3,
                'user_name' => 'Юрий',
                'email' => 'bodakyura@gmail.com',
                'google_id' => 'rwrwerwer234234',
                'user_img' => '09ffac444aec148e9b51500b6a292ac9.jpg',
                'desc' => '',
                'password' => '3f37787af5151ddde00f36233550832a',
                'user_type_id' => 3,
                'doljnost' => 'Программист',
                'delete' => '1',
            ),
            array( // row #2
                'id' => 4,
                'user_name' => 'Алексей',
                'email' => 'wokster2@gmail.com',
                'google_id' => '',
                'user_img' => 'ebe92dcc7701f72e4c12109b2049fd14.png',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 3,
                'doljnost' => 'Интернет-маркетолог',
                'delete' => '1',
            ),
            array( // row #3
                'id' => 5,
                'user_name' => 'Анна Просвирина',
                'email' => 'annlitvinova@mail.ru',
                'google_id' => 'gema@koloro.ua',
                'user_img' => '6be408d7e9726d8c7c4304f6387a604d.jpg',
                'desc' => '',
                'password' => '05641eb59d62704f1aaf5177bdc33dac',
                'user_type_id' => 2,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #4
                'id' => 7,
                'user_name' => 'Кристина',
                'email' => 'kristina.neronova@gmail.com',
                'google_id' => 'kristina.neronova@gmail.com',
                'user_img' => '15de221db951794058901f29a65f6f81.jpg',
                'desc' => '',
                'password' => '20cf0f89515b262f05d04ce904e63cff',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #5
                'id' => 8,
                'user_name' => 'Алина',
                'email' => 'alina@gmail.com',
                'google_id' => '',
                'user_img' => '2d8f39a46324ff9e552ddde12b8a7422.jpg',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #6
                'id' => 9,
                'user_name' => 'Игорь',
                'email' => 'gema@koloro.ua',
                'google_id' => '',
                'user_img' => '2e93f329ed069e68b85102f9f334e53c.jpg',
                'desc' => '',
                'password' => '7f499f9a6e01ba090e4c39084bfd3016',
                'user_type_id' => 3,
                'doljnost' => 'Руководитель',
                'delete' => '0',
            ),
            array( // row #7
                'id' => 10,
                'user_name' => 'Игорь',
                'email' => 'zzzshortyszzz@gmail.com',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 2,
                'doljnost' => 'Программист',
                'delete' => '1',
            ),
            array( // row #8
                'id' => 11,
                'user_name' => 'Project',
                'email' => 'pm@oldmin.org',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 2,
                'doljnost' => 'Программист',
                'delete' => '1',
            ),
            array( // row #9
                'id' => 12,
                'user_name' => 'Игорь Горулько',
                'email' => 'gorulko@koloro.ru',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 1,
                'doljnost' => 'Менеджер по сбыту',
                'delete' => '1',
            ),
            array( // row #10
                'id' => 13,
                'user_name' => 'Кирилл',
                'email' => 'kirifomi@mail.ru',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => '6fea462a7bbdc4b8de9b37e2adaa5e8b',
                'user_type_id' => 1,
                'doljnost' => 'Дизайнер',
                'delete' => '1',
            ),
            array( // row #11
                'id' => 14,
                'user_name' => 'Юрий',
                'email' => 'bodakyura@gmail.com',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => '827ccb0eea8a706c4c34a16891f84e7b',
                'user_type_id' => 3,
                'doljnost' => 'Программист',
                'delete' => '1',
            ),
            array( // row #12
                'id' => 15,
                'user_name' => 'Олеся',
                'email' => 'olesya@mail.ru',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #13
                'id' => 16,
                'user_name' => 'Митя Глебов',
                'email' => 'glebov@koloro.ua',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #14
                'id' => 17,
                'user_name' => 'Анна Даценко',
                'email' => 'dacenko@koloro.ua',
                'google_id' => 'https://plus.google.com/u/0/112962745449167061334/',
                'user_img' => 'b7595937c4d15948d777dc12307a97df.jpg',
                'desc' => '',
                'password' => '63cfe188d5e352db8412a91c1718ffee',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #15
                'id' => 18,
                'user_name' => 'Наталья',
                'email' => 'npiliya@mail.ru',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => '7f499f9a6e01ba090e4c39084bfd3016',
                'user_type_id' => 1,
                'doljnost' => 'gema@koloro.ua',
                'delete' => '1',
            ),
            array( // row #16
                'id' => 19,
                'user_name' => 'Доминюк Алина',
                'email' => 'dominiuk@koloro.ua',
                'google_id' => 'https://plus.google.com/u/0/101428342757745057099/posts',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => '1e82f8279e2a4ee8bb304925ea1a1925',
                'user_type_id' => 2,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #17
                'id' => 20,
                'user_name' => 'Александра Мурин',
                'email' => 'murin@koloro.ua',
                'google_id' => '',
                'user_img' => 'b9bf1bce848542a86d55d205e6479b53.jpg',
                'desc' => '',
                'password' => '7972274fd7168b76ceaeb956c3770f92',
                'user_type_id' => 1,
                'doljnost' => 'murin@koloro.ua',
                'delete' => '1',
            ),
            array( // row #18
                'id' => 21,
                'user_name' => 'Дарья Таран',
                'email' => 'taran@koloro.ua',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'c05976d5a487b4a623cc5f0641da64af',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #19
                'id' => 22,
                'user_name' => 'Дарья Таран',
                'email' => 'taran@koloro.ua',
                'google_id' => 'taran@koloro.ua',
                'user_img' => '8510fa4fea69cae7fdf61bc7d5a320f2.jpg',
                'desc' => '',
                'password' => 'c22676b26da08843a4004db6cbd0a5e3',
                'user_type_id' => 2,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #20
                'id' => 23,
                'user_name' => 'Дарья Таран',
                'email' => 'tarandaruna@gmail.com',
                'google_id' => '',
                'user_img' => 'cab92137672c5c3f786026e3ee7ba00c.jpg',
                'desc' => '',
                'password' => 'ddfa7422726458bdbb2e24206c587ce8',
                'user_type_id' => 2,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #21
                'id' => 24,
                'user_name' => 'Олег Баглык',
                'email' => 'olezhych89@gmail.com',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => '43d122e492f4b568dd5df1516f24d358',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '1',
            ),
            array( // row #22
                'id' => 25,
                'user_name' => 'Виктория Редько',
                'email' => 'viktoriia70693@mail.ru',
                'google_id' => '',
                'user_img' => '5fdf6f512d224b0b311ffd826a08306d.png',
                'desc' => '',
                'password' => '716b083c9f2ed46e1927225e7002654f',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '1',
            ),
            array( // row #23
                'id' => 26,
                'user_name' => 'Инна Дитяшова',
                'email' => 'ditiashova.inna@gmail.com',
                'google_id' => '',
                'user_img' => 'e255feada66c7c83f8c6edca05c1ad86.jpg',
                'desc' => '',
                'password' => 'ab64ea380876ce136809f064dcf4593a',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '1',
            ),
            array( // row #24
                'id' => 27,
                'user_name' => 'Александр Савенок',
                'email' => 'savenok.alexandr@gmail.com',
                'google_id' => '',
                'user_img' => '291adde142d34c69087fc00642b805ad.jpg',
                'desc' => '',
                'password' => 'c0a4125bc83caffaadbe18a2da8498f3',
                'user_type_id' => 3,
                'doljnost' => 'SEO',
                'delete' => '1',
            ),
            array( // row #25
                'id' => 28,
                'user_name' => 'Ксения Ляшко',
                'email' => 'ksenia.lyashko@gmail.com',
                'google_id' => '',
                'user_img' => '9b48daa5e9f5d37c3aa02c59342f36d0.jpg',
                'desc' => '',
                'password' => '130aaef028b3aa6fc9e18038cfb80976',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '0',
            ),
            array( // row #26
                'id' => 29,
                'user_name' => 'Анастасия Корж',
                'email' => 'korzh.anastasia97@gmail.com',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'a04f0d701ca845630122be5d15f360f3',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '1',
            ),
            array( // row #27
                'id' => 30,
                'user_name' => 'Алексей Шкуркин',
                'email' => 'alexeyskinner@gmail.com',
                'google_id' => 'gema@koloro.ua',
                'user_img' => '5c079b187a4fb77e9b9e6ecde2840f4b.png',
                'desc' => '',
                'password' => 'b4fb68eca9623851040f83ae3d1037bd',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '0',
            ),
            array( // row #28
                'id' => 31,
                'user_name' => 'Анна Сергиенко',
                'email' => 'annrium@gmail.com',
                'google_id' => '',
                'user_img' => 'ffee66d2f49ebe88f7eccef7888355ba.jpg',
                'desc' => '',
                'password' => '166f078da755dd015a8d8d662b1bb96e',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '1',
            ),
            array( // row #29
                'id' => 32,
                'user_name' => 'Маргарита Бодак',
                'email' => 'margaritabodak@gmail.com',
                'google_id' => 'gema@koloro.ua',
                'user_img' => 'f9c99cdffd33177cfd8dcdf5e8ed38fa.jpg',
                'desc' => '',
                'password' => '65c9dc40ac03bfbc3f43b71dd8fb9986',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '1',
            ),
            array( // row #30
                'id' => 33,
                'user_name' => 'Екатерина Барановская',
                'email' => 'kate.baranovska@gmail.com',
                'google_id' => '',
                'user_img' => 'd946dd55d39df19b40a662977f769c28.jpg',
                'desc' => '',
                'password' => '869bb9e8ce6fda80127e0fa2fb2903e0',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '1',
            ),
            array( // row #31
                'id' => 34,
                'user_name' => 'Александр Дихтярук',
                'email' => 'dikhtyaruk@koloro.ua',
                'google_id' => '',
                'user_img' => 'fa6c94fb063bba36590b946a5c0a17a4.png',
                'desc' => '',
                'password' => 'e800fa5de0352b7dc4fd2d8162f09f7c',
                'user_type_id' => 2,
                'doljnost' => 'Руководитель отдела маркетинга',
                'delete' => '1',
            ),
            array( // row #32
                'id' => 35,
                'user_name' => 'Мария Волошина',
                'email' => 'voloshkamasha@gmail.com',
                'google_id' => '',
                'user_img' => '15d1a9c31ae3bd0fd0c4f8e265541256.png',
                'desc' => '',
                'password' => '6287687a2e189096aef3763816ef00a0',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '0',
            ),
            array( // row #33
                'id' => 36,
                'user_name' => 'Людмила Шуба',
                'email' => 'lucyou91@gmail.com',
                'google_id' => '',
                'user_img' => 'b9824b7cf9db2e39b87521423bc4aa52.png',
                'desc' => '',
                'password' => '6287687a2e189096aef3763816ef00a0',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #34
                'id' => 37,
                'user_name' => 'Ольга Парасий',
                'email' => 'ovparasii@gmail.com',
                'google_id' => '',
                'user_img' => '13b4e954df0293cc3e808a6e8ae68d55.jpg',
                'desc' => '',
                'password' => '6',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #35
                'id' => 38,
                'user_name' => 'Александр Тоболин',
                'email' => 'tozik1994@gmail.com',
                'google_id' => '',
                'user_img' => '52b77ee231853d20723e2c4b348061aa.jpg',
                'desc' => '',
                'password' => '1b464fff96278480fd31edf5c21c878a',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '0',
            ),
            array( // row #36
                'id' => 39,
                'user_name' => 'Анна Слёз',
                'email' => 'anya.sleoz@yandex.ua',
                'google_id' => '',
                'user_img' => '92fa709f476f105b2d219fb53d466058.jpg',
                'desc' => '',
                'password' => '3e1669b97a420619b46aadeb17348d13',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #37
                'id' => 40,
                'user_name' => 'Дария Мех',
                'email' => 'dariiamekh@gmail.com',
                'google_id' => '',
                'user_img' => 'd12aeb0f05e0232e498513f0780c31df.jpg',
                'desc' => '',
                'password' => '5f4eaea2280ab3b0c26fa81381f0f362',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '0',
            ),
            array( // row #38
                'id' => 41,
                'user_name' => 'Виктор Волков',
                'email' => 'vktrvlkff@gmail.com',
                'google_id' => '',
                'user_img' => '76dbb76f060ea62ca5e6bd864ceb3b59.jpg',
                'desc' => '',
                'password' => 'e2b49aff1d49566a92beeba5e8472efb',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '0',
            ),
            array( // row #39
                'id' => 42,
                'user_name' => 'Глеб Остриков',
                'email' => 'ostgleal@gmail.com',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => '748ce16a3c2edecd90511c2123b713c5',
                'user_type_id' => 1,
                'doljnost' => 'Программист',
                'delete' => '0',
            ),
            array( // row #40
                'id' => 43,
                'user_name' => 'Яна Галака',
                'email' => 'yana.galaka@gmail.com',
                'google_id' => '',
                'user_img' => '043751c576874d159b1de1bfe1271280.jpg',
                'desc' => '',
                'password' => '35474dba2d93d915678c531f1574e64e',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '0',
            ),
            array( // row #41
                'id' => 44,
                'user_name' => 'Олег Сметана',
                'email' => 'smetua91@gmail.com',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => '37ba9e24325e81ff594713bd94b2c3e5',
                'user_type_id' => 3,
                'doljnost' => 'SEO',
                'delete' => '0',
            ),
            array( // row #41
                'id' => 45,
                'user_name' => 'Александр Копытов',
                'email' => 'shadowflame724@gmail.com',
                'google_id' => '',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => '37ba9e24325e81ff594713bd94b2c3e5',
                'user_type_id' => 3,
                'doljnost' => 'SEO',
                'delete' => '0',
            )
        );

        foreach ($oldUsers as $user) {
            $file = new \App\Models\File;
            $file->link = $user['user_img'];
            $file->save();

            $newUsersArr = [
                'id' => $user['id'],
                'name' => $user['user_name'],
                'email' => $user['email'],
                'password' => bcrypt($user['email']),
                'image_id' => $file->id,
                'post' => $user['doljnost'],
                'google' => null,
                'phone' => null,
                'about' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'status' => 0
            ];
            DB::table('users')->insert($newUsersArr);
            DB::table('role_user')->truncate();
            DB::table('role_user')->insert([
                'user_id' => $user['id'],
                'role_id' => 3
            ]);
        }

    }
}
