<?php

use Illuminate\Database\Seeder;

class OldUsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('users')->truncate();

        $oldUsers = array(
            array( // row #0
                'id' => 1,
                'name' => 'Воскан',
                'email' => 'info@voskan-voskanyan.ru',
                'user_img' => 'd8ca083788944f2614ca5c571d12e2e9.jpg',
                'desc' => '',
                'password' => 'fd9280bc68d29f9becaaa62fc86bcbe8',
                'user_type_id' => 3,
                'doljnost' => 'Программист',
                'delete' => '1',
            ),
            array( // row #1
                'id' => 3,
                'name' => 'Юрий',
                'email' => 'bodakyura1@gmail.com',
                'user_img' => '09ffac444aec148e9b51500b6a292ac9.jpg',
                'desc' => 'test',
                'password' => '3f37787af5151ddde00f36233550832a',
                'user_type_id' => 3,
                'doljnost' => 'Программист',
                'delete' => '1',
            ),
            array( // row #2
                'id' => 4,
                'name' => 'Алексей',
                'email' => 'wokster2@gmail.com',
                'user_img' => 'ebe92dcc7701f72e4c12109b2049fd14.png',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 3,
                'doljnost' => 'Интернет-маркетолог',
                'delete' => '1',
            ),
            array( // row #3
                'id' => 5,
                'name' => 'Анна Просвирина',
                'email' => 'annlitvinova@mail.ru',
                'user_img' => '6be408d7e9726d8c7c4304f6387a604d.jpg',
                'desc' => '',
                'password' => '8a8c2b26f4840bad5cad276116ee8ef8',
                'user_type_id' => 2,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #4
                'id' => 7,
                'name' => 'Кристина',
                'email' => 'kristina.neronova@gmail.com',
                'user_img' => '7c2d45f90f70c39d2a001922fa219fe7.jpg',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #5
                'id' => 8,
                'name' => 'Алина',
                'email' => 'alina@gmail.com',
                'user_img' => '2d8f39a46324ff9e552ddde12b8a7422.jpg',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #6
                'id' => 9,
                'name' => 'Игорь',
                'email' => 'gema@koloro.ua',
                'user_img' => '6f91a028d705029321479835cce4b00a.jpg',
                'desc' => '',
                'password' => '7f499f9a6e01ba090e4c39084bfd3016',
                'user_type_id' => 3,
                'doljnost' => 'Руководитель',
                'delete' => '0',
            ),
            array( // row #7
                'id' => 10,
                'name' => 'Игорь',
                'email' => 'zzzshortyszzz@gmail.com',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 2,
                'doljnost' => 'Программист',
                'delete' => '1',
            ),
            array( // row #8
                'id' => 11,
                'name' => 'Project',
                'email' => 'pm@oldmin.org',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 2,
                'doljnost' => 'Программист',
                'delete' => '1',
            ),
            array( // row #9
                'id' => 12,
                'name' => 'Игорь Горулько',
                'email' => 'gorulko@koloro.ru',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 1,
                'doljnost' => 'Менеджер по сбыту',
                'delete' => '1',
            ),
            array( // row #10
                'id' => 13,
                'name' => 'Кирилл',
                'email' => 'kirifomi@mail.ru',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => '6fea462a7bbdc4b8de9b37e2adaa5e8b',
                'user_type_id' => 1,
                'doljnost' => 'Дизайнер',
                'delete' => '1',
            ),
            array( // row #11
                'id' => 14,
                'name' => 'Юрий',
                'email' => 'bodakyura@gmail.com',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => '827ccb0eea8a706c4c34a16891f84e7b',
                'user_type_id' => 3,
                'doljnost' => 'Программист',
                'delete' => '1',
            ),
            array( // row #12
                'id' => 15,
                'name' => 'Олеся',
                'email' => 'olesya@mail.ru',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #13
                'id' => 16,
                'name' => 'Митя Глебов',
                'email' => 'glebov@koloro.ua',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'aeb15a916bc4f2a9cf2ac86c7888444c',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #14
                'id' => 17,
                'name' => 'Анна Даценко',
                'email' => 'dacenko@koloro.ua',
                'user_img' => 'ef6a255d1764a75a91015d1094c51441.jpg',
                'desc' => '',
                'password' => '63cfe188d5e352db8412a91c1718ffee',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #15
                'id' => 18,
                'name' => 'Дарья Таран',
                'email' => 'taran@koloro.ua',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'c22676b26da08843a4004db6cbd0a5e3',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #16
                'id' => 19,
                'name' => 'Дарья Таран',
                'email' => 'taran1@koloro.ua',
                'user_img' => '8e82dad8831c467e3b8e7044e7c88144.jpg',
                'desc' => '',
                'password' => 'c22676b26da08843a4004db6cbd0a5e3',
                'user_type_id' => 2,
                'doljnost' => 'taran@koloro.ua',
                'delete' => '1',
            ),
            array( // row #17
                'id' => 20,
                'name' => 'Дарья Таран',
                'email' => 'tarandaruna@gmail.com',
                'user_img' => '3e4f4aefdb077db9dacf1c3a35a2e883.jpg',
                'desc' => '',
                'password' => 'ddfa7422726458bdbb2e24206c587ce8',
                'user_type_id' => 2,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #18
                'id' => 21,
                'name' => 'Олег Баглык',
                'email' => 'olezhych89@gmail.com',
                'user_img' => 'cfa0b60be5fdb70002af22da10849cf0.jpg',
                'desc' => '',
                'password' => '21cfd2ec89fd44be9df405680a8f2f3e',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '1',
            ),
            array( // row #19
                'id' => 22,
                'name' => 'Виктория Редько',
                'email' => 'viktoriia70693@mail.ru',
                'user_img' => 'fb567304d7b10adff340434a7e3e0434.png',
                'desc' => '',
                'password' => '4414bc138d9a5020879f27c917baffaa',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '1',
            ),
            array( // row #20
                'id' => 23,
                'name' => 'Инна Дитяшова',
                'email' => 'ditiashova.inna@gmail.com',
                'user_img' => '5740453df3533f0242672947bb7fd4e9.jpg',
                'desc' => '',
                'password' => '81b071f662c46480b5f064a8ffc13484',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '1',
            ),
            array( // row #21
                'id' => 24,
                'name' => 'Александр Савенок',
                'email' => 'savenok.alexandr@gmail.com',
                'user_img' => '0d84e64640bf6617fb708b73a41c2e09.jpg',
                'desc' => '',
                'password' => '73de15aa6697f0e5b79309c098aa0f58',
                'user_type_id' => 3,
                'doljnost' => 'SEO',
                'delete' => '1',
            ),
            array( // row #22
                'id' => 25,
                'name' => 'Ксения Ляшко',
                'email' => 'ksenia.lyashko@gmail.com',
                'user_img' => 'a6d72c03b8086b9484e426f2663e3ede.jpg',
                'desc' => '',
                'password' => 'd8a9b41736bb240650ab07bae3839f66',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '0',
            ),
            array( // row #23
                'id' => 26,
                'name' => 'Маргарита Бодак',
                'email' => 'margaritabodak@gmail.com',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'a9a7deb93c7d4836b6d806420e753668',
                'user_type_id' => 1,
                'doljnost' => 'Копирайтер',
                'delete' => '1',
            ),
            array( // row #24
                'id' => 27,
                'name' => 'Александр Дихтярук',
                'email' => 'dikhtyaruk@koloro.ua',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'bb1d687c0fb479e3146a7135bc4884fb',
                'user_type_id' => 2,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #25
                'id' => 28,
                'name' => 'Александр Тоболин',
                'email' => 'tozik1994@gmail.com',
                'user_img' => '99d7fa43075092f04a3d6e99747c7b0b.jpg',
                'desc' => '',
                'password' => '1b464fff96278480fd31edf5c21c878a',
                'user_type_id' => 3,
                'doljnost' => 'Маркетолог',
                'delete' => '0',
            ),
            array( // row #26
                'id' => 29,
                'name' => 'Мария Волошина',
                'email' => 'voloshkamasha@gmail.com',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => '6287687a2e189096aef3763816ef00a0',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '0',
            ),
            array( // row #27
                'id' => 30,
                'name' => 'Анна Слёз',
                'email' => 'anya.sleoz@yandex.ua',
                'user_img' => '70a702a376ad5b07e97ad18b198e40bc.jpg',
                'desc' => '',
                'password' => '3e1669b97a420619b46aadeb17348d13',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #28
                'id' => 31,
                'name' => 'Людмила Шуба',
                'email' => 'lucyou91@gmail.com',
                'user_img' => 'default.png',
                'desc' => '',
                'password' => 'bda99820d083b141aab22aef41838bc3',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '0',
            ),
            array( // row #29
                'id' => 32,
                'name' => 'Людмила Шуба',
                'email' => 'alex.diht@gmail.com',
                'user_img' => '5d8c3d5ee923f39d67a8386821dc71ee.png',
                'desc' => '',
                'password' => '6287687a2e189096aef3763816ef00a0',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '1',
            ),
            array( // row #30
                'id' => 33,
                'name' => 'Дария Мех',
                'email' => 'dariiamekh@gmail.com',
                'user_img' => '80f30ca13990a81ae541606c570fb628.jpg',
                'desc' => '',
                'password' => '5f4eaea2280ab3b0c26fa81381f0f362',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '0',
            ),
            array( // row #31
                'id' => 34,
                'name' => 'Виктор Волков',
                'email' => 'vktrvlkff@gmail.com',
                'user_img' => '31fec81fd18a9db5048feb1298476686.jpg',
                'desc' => '',
                'password' => 'e2b49aff1d49566a92beeba5e8472efb',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '0',
            ),
            array( // row #32
                'id' => 35,
                'name' => 'Глеб Остриков',
                'email' => 'ostgleal@gmail.com',
                'user_img' => '65b40583445627080d0b5a0566b2e5d6.jpg',
                'desc' => '',
                'password' => '748ce16a3c2edecd90511c2123b713c5',
                'user_type_id' => 3,
                'doljnost' => 'Программист',
                'delete' => '0',
            ),
            array( // row #33
                'id' => 36,
                'name' => 'Олег Сметана',
                'email' => 'smetua91@gmail.com',
                'user_img' => '0e97a5101c49b572bcd33fe5f2ee9153.jpg',
                'desc' => '',
                'password' => 'ea513ee044a8c9965c60cf7eeb9bf3de',
                'user_type_id' => 3,
                'doljnost' => 'SEO',
                'delete' => '0',
            ),
            array( // row #34
                'id' => 37,
                'name' => 'Яна Галака',
                'email' => 'yana.galaka@gmail.com',
                'user_img' => '22e0a1c32fc75cb1cde5107289955de2.jpg',
                'desc' => '',
                'password' => '35474dba2d93d915678c531f1574e64e',
                'user_type_id' => 1,
                'doljnost' => 'Маркетолог',
                'delete' => '0',
            ),
            array( // row #35
                'id' => 38,
                'name' => 'Александр Копытов',
                'email' => 'shadowflame724@gmail.com',
                'user_img' => '111',
                'desc' => '',
                'password' => bcrypt('cfirf534520390'),
                'user_type_id' => 1,
                'doljnost' => 'Back-end dev',
                'delete' => '0',
            ),
        );

        foreach ($oldUsers as $user) {
            $file = new \App\Models\File;
            $file->link = $user['user_img'];
            $file->save();

            $newUsersArr = [
                'id' => $user['id'],
                'name' => $user['name'],
                'email' => $user['email'],
                'password' => bcrypt($user['email']),
                'image_id' => $file->id,
                'post' => $user['doljnost'],
                'google' => null,
                'phone' => null,
                'about' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => null,
                'status' => 0
            ];
            DB::table('users')->insert($newUsersArr);
            DB::table('role_user')->insert([
                'user_id' => $user['id'],
                'role_id' => 3
            ]);
        }

    }
}
